### ISSUE TITLE
[Feature] Add check number option in Armstrong Number Calculator

### ISSUE THREAD

**Issue by saurabhhsinghh** [Rakesh9100/CalcDiverse#1918] opened 2024-12-16 12:07 UTC
### Description

The Armstrong Number Check Calculator can be used to determine whether a given number is an Armstrong number or not. Armstrong numbers are special numbers where the sum of their digits raised to the power of the number of digits equals the original number itself.

### Screenshots

![Screenshot 2024-12-16 173645](https://github.com/user-attachments/assets/c5684f97-7124-4782-ae17-d3d838ef41b4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SHRUTISINHA250714** [comment] 2024-12-16 18:20
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by Rakesh9100** [comment] 2024-12-16 20:03
We already have Armstrong Number Calculator, lmk further @saurabhhsinghh

**Comment by saurabhhsinghh** [comment] 2024-12-17 07:38
CalcDiverse doesn't include an Armstrong number checker; instead, it features a calculator that generates Armstrong numbers based on the number of digits you input.

![Screenshot 2024-12-17 130344](https://github.com/user-attachments/assets/609fb85c-03d7-4796-91d9-77cc8719ff63)

**Comment by Rakesh9100** [comment] 2024-12-17 17:07
You can integrate this feature in this same calculator by designing a seamless UI, no need of separate one @saurabhhsinghh

**Comment by saurabhhsinghh** [comment] 2024-12-17 19:40
Yes, I can work on that. Kindly assign the issue to me

**Comment by Rakesh9100** [comment] 2024-12-18 04:11
Okay, proceed @saurabhhsinghh

**Closed** 2024-12-20 19:48 UTC
Labels: KWOC
