### ISSUE TITLE
[Style] Enhance the navbar logo text hover effect

### ISSUE THREAD

**Issue by Ajai-Sharan** [Rakesh9100/CalcDiverse#1928] opened 2024-12-19 06:49 UTC
### What's the style idea?

**Description**:  
In both light mode and dark mode of the CAL Diverse application, the logo's text hover color changes to pink. This behavior is inconsistent with the overall UI/UX theme and does not adapt to the respective mode's color scheme.

**Screenshots**:
![image](https://github.com/user-attachments/assets/a30dc5f2-c067-45fb-aa96-e3c3c77ea245)
![image](https://github.com/user-attachments/assets/6926faab-6f88-410e-8177-40f025982089)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Ajai-Sharan** [comment] 2024-12-19 06:50
@Rakesh9100  I would like to work on this issue. Please assign this issue to me.

**Comment by isid555** [comment] 2024-12-19 06:55
@Ajai-Sharan  I have already raised the same issue #1927
Kindly check before raising issues if they are already existing , Im also assigned to it
Thank you

**Comment by Rakesh9100** [comment] 2024-12-19 07:03
The issue is already open for this, please work on other issues @Ajai-Sharan

**Comment by Ajai-Sharan** [comment] 2024-12-19 17:58
@isid555 I went through your issue. You've raised issue on navigation texts in navbar but I am taking about the text near logo. while hovering over the text near the logo it is in pink in color in both light and dark mode and it is not going well with the theme of the light mode.

screenshots:
![Screenshot 2024-12-19 231949](https://github.com/user-attachments/assets/fa13b6d5-4157-4cf4-93b8-a201a5d3346d)
![Screenshot 2024-12-19 232007](https://github.com/user-attachments/assets/a403a409-870c-4bdc-9702-955eee421d32)

@Rakesh9100 please kindly open the issue and assign it to me.

**Comment by isid555** [comment] 2024-12-20 05:20
@Ajai-Sharan  Fine....Your Issue title and its desciption were very different ....so was the confusion.

**Comment by Rakesh9100** [comment] 2024-12-20 19:51
Okay, proceed @Ajai-Sharan

**Closed** 2024-12-23 05:04 UTC
Labels: KWOC
