### ISSUE TITLE
Adding a permutation and combination calculator 

### ISSUE THREAD

**Issue by JATIN0926** [Rakesh9100/CalcDiverse#94] opened 2024-01-04 18:32 UTC
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Addition of a calculator which will take inputs of n and r and will calculate ncr and npr for users 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/CalcDiverse/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment] 2024-01-05 22:18
@JATIN0926 Update of your PR pls

**Comment by Jainil2004** [comment] 2024-01-06 17:54
hello @Rakesh9100, i would like to contribute to your project and would love to solve this issue. if the issue is still open can you please assign it to me? also would really appreciate if you could provide me with some details about how the issue has to be resolved and what are the changes you are expecting.
Thank you

**Comment by Rakesh9100** [comment] 2024-01-07 06:26
@JATIN0926 Are you working

**Comment by JATIN0926** [comment] 2024-01-07 07:03
Yes , I am working on it I will submit it by today

**Closed** 2024-01-08 04:38 UTC
Labels: enhancement, SWOC S4, Hard, calculator addition 📱
